homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto:1883
serial:
  port: /dev/ttyUSB0
  adapter: zstack
frontend:
  enabled: true
  port: 8099
advanced:
  log_level: info
version: 5
