"""Generate hacs-manifest.yaml from HACS's install record (.storage/hacs.repositories).

Runs on blacky (the only host with the store). Pure transform + a thin CLI.
"""
import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

GITHUB = "https://github.com/"


def load_store(path: str) -> list[dict]:
    """Return the list of repo dicts from a HACS .storage/hacs.repositories file.

    The HA store wraps the payload as {"data": [...]}; tolerate a bare list/dict too.
    Raises FileNotFoundError if absent, ValueError if the JSON is malformed.
    """
    with open(path, encoding="utf-8") as fh:
        try:
            doc = json.load(fh)
        except json.JSONDecodeError as err:
            raise ValueError(f"malformed HACS store at {path}: {err}") from err
    data = doc.get("data", doc) if isinstance(doc, dict) else doc
    if isinstance(data, dict):
        return list(data.values())
    return list(data)


def _pin(repo: dict) -> str:
    tag = repo.get("version_installed")
    if tag:
        return str(tag)
    return f"commit:{repo.get('installed_commit', '')}"


def installed_plugins(rows: list[dict]) -> list[dict]:
    """Filter to installed repos and normalize to manifest records, sorted by name.

    `source` defaults to "custom-repo" (the always-works restore path) because
    default-store membership can't be determined offline; a human may correct it.
    """
    out = []
    for r in rows:
        if not isinstance(r, dict):
            continue
        # `version_installed` set with installed False = installed-then-removed
        # leftover; spec intent is to include it (HACS-side cleanup may lag).
        if not (r.get("installed") or r.get("version_installed")):
            continue
        full = r.get("full_name", "")
        out.append({
            "full_name": full,
            "domain": r.get("domain", ""),
            "category": r.get("category", ""),
            "version": _pin(r),
            "source": "custom-repo",
            "repo": GITHUB + full,
        })
    out.sort(key=lambda p: p["full_name"].lower())
    return out


HEADER = """\
# HACS plugin manifest — generated by scripts/gen_hacs_manifest.py on blacky.
# Do not hand-edit. Regenerate after installing/updating a HACS plugin, then commit:
#   sudo python3 scripts/gen_hacs_manifest.py
#
# REBUILD RUNBOOK (HACS-managed restore):
#   1. Install HACS (hacs/integration) per the official docs; restart HA.
#   2. For each plugin below:
#        - source: custom-repo   -> HACS > (⋮) Custom repositories: add `repo` with
#                                    the listed `category`, then install at `version`.
#        - source: default-store -> search `full_name` in HACS, install at `version`.
#   3. Restart HA. Re-link config entries — tokens/pairings live in .storage, not git.
"""


def render_manifest(plugins: list[dict]) -> str:
    lines = [HEADER, "plugins:"]
    for p in plugins:
        lines.append(f"  - full_name: {p['full_name']}")
        lines.append(f"    domain: {p['domain']}")
        lines.append(f"    category: {p['category']}")
        lines.append(f"    version: '{p['version']}'")
        lines.append(f"    source: {p['source']}")
        lines.append(f"    repo: {p['repo']}")
    return "\n".join(lines) + "\n"


def resolve_storage_path(explicit: str | None, env=None) -> str:
    env = os.environ if env is None else env
    if explicit:
        return explicit
    user = env.get("SUDO_USER")
    if user:
        return f"/home/{user}/homeassistant/config/.storage/hacs.repositories"
    return str(Path.home() / "homeassistant/config/.storage/hacs.repositories")


def _default_out() -> str:
    return str(Path(__file__).resolve().parents[1] / "hacs-manifest.yaml")


def _write_atomic(text: str, out_path: str) -> None:
    out = Path(out_path)
    fd, tmp = tempfile.mkstemp(dir=str(out.parent), suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, out_path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Generate hacs-manifest.yaml from HACS's store.")
    p.add_argument("--storage", default=None, help="path to .storage/hacs.repositories")
    p.add_argument("--out", default=None, help="manifest output path")
    args = p.parse_args(argv)

    storage = resolve_storage_path(args.storage)
    out = args.out or _default_out()
    try:
        rows = load_store(storage)
    except FileNotFoundError:
        print(f"HACS store not found: {storage}\n"
              f"Run on blacky with sudo, or pass --storage.", file=sys.stderr)
        return 2
    except ValueError as err:
        print(str(err), file=sys.stderr)
        return 2

    plugins = installed_plugins(rows)
    if not plugins:
        print(f"No installed plugins found in {storage} — wrong path?", file=sys.stderr)
        return 1

    _write_atomic(render_manifest(plugins), out)
    print(f"Wrote {out} with {len(plugins)} plugins.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
