#!/usr/bin/env python3
"""
Regenerate config/template/fans.yaml from scripts/rf_codes_cache.json.

Partial-safe: cache accumulates codes across sessions.
Re-learning: run scripts/learn_rf_codes.py, then re-run this script.
Named commands (no b64) = not yet learned — HA will warn but not crash.

Run ON blacky (writes fans.yaml in place).

Usage:
  python3 scripts/sync_rf_codes.py               # fetch from broadlinkmanager + write
  python3 scripts/sync_rf_codes.py --cache-only  # regenerate from cache, no fetch
  python3 scripts/sync_rf_codes.py --dry-run     # print fans.yaml, don't write
  python3 scripts/sync_rf_codes.py --restart     # restart HA after writing

Requires: pip install requests
"""
import argparse
import base64
import json
import subprocess
import pathlib
import sys

try:
    import requests
except ImportError:
    sys.exit("pip install requests")

REPO_ROOT  = pathlib.Path(__file__).parent.parent
CACHE_FILE = REPO_ROOT / "scripts" / "rf_codes_cache.json"
FANS_FILE  = REPO_ROOT / "scripts" / "fans.json"
FANS_YAML  = REPO_ROOT / "config" / "template" / "fans.yaml"
RM4_ENTITY = "remote.broadlink_main_ac_and_fans"


def load_fans():
    cfg = json.loads(FANS_FILE.read_text())
    return cfg["fans"], cfg["types"]


def encode(codes: dict, device: str, command: str) -> str:
    key = f"{device}/{command}"
    if key in codes:
        return f'"b64:{codes[key]}"'
    return f'"{command}"'


def action_block(codes: dict, device: str, command: str, indent: int = 8) -> str:
    pad = " " * indent
    return (
        f"{pad}- action: remote.send_command\n"
        f"{pad}  target:\n"
        f"{pad}    entity_id: {RM4_ENTITY}\n"
        f"{pad}  data: {{device: {device}, command: {encode(codes, device, command)}}}"
    )


def _condition_block(condition: str, codes: dict, device: str, command: str) -> str:
    return (
        f"          - conditions: \"{condition}\"\n"
        f"            sequence:\n"
        f"{action_block(codes, device, command, indent=14)}"
    )


def speed_choose(codes: dict, device: str, speeds: list) -> str:
    blocks = [
        _condition_block(f"{{{{ preset_mode == '{s}' }}}}", codes, device, f"speed_{s}")
        for s in speeds
    ]
    return "      - choose:\n" + "\n".join(blocks)


def color_temp_choose(codes: dict, device: str) -> str:
    return "\n".join([
        "      - choose:",
        _condition_block("{{ color_temp_kelvin > 5000 }}", codes, device, "light_cool"),
        _condition_block("{{ color_temp_kelvin < 3500 }}", codes, device, "light_warm"),
        "        default:",
        action_block(codes, device, "light_natural", indent=10),
    ])


def brightness_choose(codes: dict, device: str) -> str:
    return "\n".join([
        "      - choose:",
        _condition_block(
            "{{ brightness > state_attr(this.entity_id, 'brightness') | int(128) }}",
            codes, device, "light_brighter",
        ),
        "        default:",
        action_block(codes, device, "light_dimmer", indent=10),
    ])


def generate(codes: dict) -> str:
    fans, types = load_fans()

    lines = [
        "# DO NOT EDIT — generated by scripts/sync_rf_codes.py",
        "# Source of truth: scripts/rf_codes_cache.json + scripts/fans.json",
        "# Named commands (no b64) = not yet learned; HA will warn but not crash.",
        "",
        "- fan:",
    ]

    for fan in fans:
        dev  = fan["id"]
        name = fan["name"]
        t    = types[fan["type"]]
        speeds = t["speeds"]
        preset_modes = "\n".join(f'      - "{s}"' for s in speeds)

        lines += [
            f'  - name: "{name}"',
            f"    unique_id: {dev}",
            f"    preset_modes:",
            preset_modes,
            f"    turn_on:",  action_block(codes, dev, t["turn_on"]),
            f"    turn_off:", action_block(codes, dev, t["turn_off"]),
            f"    set_preset_mode:", speed_choose(codes, dev, speeds),
            f"    set_direction:", action_block(codes, dev, "direction"),
        ]

    lines += ["", "- light:"]
    for fan in fans:
        dev  = fan["id"]
        name = fan["name"]
        t    = types[fan["type"]]

        lines += [f'  - name: "{name} Light"', f"    unique_id: light_{dev}"]

        if t["light"] == "toggle":
            lines += [
                "    turn_on:",  action_block(codes, dev, "light_toggle"),
                "    turn_off:", action_block(codes, dev, "light_toggle"),
            ]
        else:
            lines += [
                "    turn_on:",         action_block(codes, dev, "light_warm"),
                "    turn_off:",        action_block(codes, dev, "light_off"),
                "    set_temperature:", color_temp_choose(codes, dev),
                "    set_level:",       brightness_choose(codes, dev),
            ]

    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description="Sync RF codes from broadlinkmanager to fans.yaml")
    p.add_argument("--host",       default="localhost",  help="broadlinkmanager host (default: localhost)")
    p.add_argument("--cache-only", action="store_true", help="Skip fetch, regenerate from cache")
    p.add_argument("--dry-run",    action="store_true", help="Print fans.yaml, don't write")
    p.add_argument("--restart",    action="store_true", help="Restart HA after writing fans.yaml")
    args = p.parse_args()

    codes = json.loads(CACHE_FILE.read_text()) if CACHE_FILE.exists() else {}
    print(f"Cache: {len(codes)} codes")

    if not args.cache_only:
        print(f"Fetching http://{args.host}:7020/api/codes ...")
        r = requests.get(f"http://{args.host}:7020/api/codes", timeout=5)
        r.raise_for_status()
        raw = r.json()
        if not isinstance(raw, list):
            sys.exit(f"Unexpected API response (expected list): {raw}")
        new = {
            c["CodeName"]: base64.b64encode(bytes.fromhex(c["Code"])).decode()
            for c in raw
            if "/" in c.get("CodeName", "")
        }
        print(f"  +{len(new)} codes from broadlinkmanager")
        codes.update(new)
        CACHE_FILE.write_text(json.dumps(codes, indent=2, sort_keys=True))
        print(f"Cache saved: {len(codes)} total")

    yaml_out = generate(codes)

    if args.dry_run:
        print(yaml_out)
        return

    FANS_YAML.write_text(yaml_out)
    print(f"Written: {FANS_YAML}")

    if args.restart:
        print("Restarting HA ...")
        subprocess.run(
            ["docker", "compose", "-f", str(REPO_ROOT / "docker-compose.yml"),
             "restart", "homeassistant"],
            check=True,
        )
        print("HA restarting.")
    else:
        print("Restart HA: cd ~/homeassistant && docker compose restart homeassistant")


if __name__ == "__main__":
    main()
